// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC98YoRsgOF1fYvHxd2PsoNMM-ig7NcAWQ',
    appId: '1:1044048419847:web:8b57a9e93c60a537965ea2',
    messagingSenderId: '1044048419847',
    projectId: 'handong-dorm-manager',
    authDomain: 'handong-dorm-manager.firebaseapp.com',
    storageBucket: 'handong-dorm-manager.firebasestorage.app',
    measurementId: 'G-QRD4VEX8Y1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQrqFEH_50zeXZdzgwQ73eTl3QmtHJjy8',
    appId: '1:1044048419847:android:1608d4d7a402695e965ea2',
    messagingSenderId: '1044048419847',
    projectId: 'handong-dorm-manager',
    storageBucket: 'handong-dorm-manager.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClOcG0h4bkOgA5KH6J4fzHe7CmLyfiN8w',
    appId: '1:1044048419847:ios:08cf42229a6e4510965ea2',
    messagingSenderId: '1044048419847',
    projectId: 'handong-dorm-manager',
    storageBucket: 'handong-dorm-manager.firebasestorage.app',
    iosClientId: '1044048419847-8u8q7fgv1sgrv530qr2fqgi6ovio9jhn.apps.googleusercontent.com',
    iosBundleId: 'com.example.mdc100Series',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClOcG0h4bkOgA5KH6J4fzHe7CmLyfiN8w',
    appId: '1:1044048419847:ios:08cf42229a6e4510965ea2',
    messagingSenderId: '1044048419847',
    projectId: 'handong-dorm-manager',
    storageBucket: 'handong-dorm-manager.firebasestorage.app',
    iosClientId: '1044048419847-8u8q7fgv1sgrv530qr2fqgi6ovio9jhn.apps.googleusercontent.com',
    iosBundleId: 'com.example.mdc100Series',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC98YoRsgOF1fYvHxd2PsoNMM-ig7NcAWQ',
    appId: '1:1044048419847:web:04cf4fcf2165ede6965ea2',
    messagingSenderId: '1044048419847',
    projectId: 'handong-dorm-manager',
    authDomain: 'handong-dorm-manager.firebaseapp.com',
    storageBucket: 'handong-dorm-manager.firebasestorage.app',
    measurementId: 'G-Y1JL7VFG56',
  );
}
